export const ERASMUS_THEMES = [
  "Performing Arts",
  "Climate Change",
  "Digital Skills",
  "Social Inclusion",
  "Youth Work",
  "Mental Health",
  "Entrepreneurship",
  "Agriculture & Rural Development",
  "Civic Engagement",
  "Cultural Heritage",
  "Democracy",
  "Disability",
  "Eco-living & Sustainability",
  "Education & Training",
  "Employment & Career",
  "Environment & Nature",
  "European Citizenship",
  "Gender Equality",
  "Health & Wellbeing",
  "Human Rights",
  "Intercultural Dialogue",
  "Language Learning",
  "Leadership",
  "LGBTQ+ Issues",
  "Media Literacy",
  "Migration & Refugees",
  "Minorities",
  "Music & Arts",
  "Outdoor Education",
  "Peacebuilding",
  "Policy Making",
  "Racism & Discrimination",
  "Roma Communities",
  "Science & Technology",
  "Social Entrepreneurship",
  "Social Media",
  "Solidarity",
  "Sports & Physical Activities",
  "Sustainable Development Goals (SDGs)",
  "Volunteering",
  "Youth Participation",
  "Youth Policy"
];
